In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
# load dataset

df_original = pd.read_csv('Data_features.csv') # feature set
obs = pd.read_csv('Data_train_set.csv') # User ID, Churn
est = pd.read_csv('Data_test_set.csv')  # User ID to predict Churn
obs_id = obs['ID'].values # IDs in factual data
est_id = est['ID'].values # IDs to analyse
df = df_original[df_original.ID.isin(obs_id)] # df for training
df_lm = df[df.MONTH_NUM_FROM_EVENT == 1] # the last month data
X = np.array(df_lm.values)[:,2:] # array of features from 
y = np.array(obs.TARGET)

from sklearn.utils.validation import assert_all_finite
nanplaces = np.isnan(X)
X[nanplaces] = 0
# run checks
print(assert_all_finite(X))
# should output None
print(np.any(np.isnan(X)), np.all(np.isfinite(X))) 
# should output False True

None
False True


In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=6)

In [3]:
from sklearn.linear_model import LogisticRegression

In [5]:
C = 0.01
for solver in ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']:
    LR = LogisticRegression(C=0.2, solver=solver, max_iter=8000)
    LR.fit(X_train,y_train)
    y_prob_ = LR.predict_proba(X_test)[:,1]
    y_ = LR.predict(X_test)
    print('C =', C, 'using', solver, 'solver')
    print(confusion_matrix(y_test, y_, labels=[1,0]))
    print("AUC ROC score", roc_auc_score(y_test, y_prob_))

C = 0.01 using newton-cg solver
[[   2  195]
 [   3 2378]]
AUC ROC score 0.7717420270883921
C = 0.01 using lbfgs solver
[[   4  193]
 [   3 2378]]
AUC ROC score 0.7663866012019861
C = 0.01 using liblinear solver
[[   4  193]
 [   3 2378]]
AUC ROC score 0.7682499141895336
C = 0.01 using sag solver
[[   1  196]
 [   3 2378]]
AUC ROC score 0.7003200037522093
C = 0.01 using saga solver
[[   1  196]
 [   2 2379]]
AUC ROC score 0.6937898805475667


In [6]:
for solver in ['newton-cg', 'lbfgs', 'liblinear']:
    LR = LogisticRegression(C=0.021, solver=solver, max_iter=8000)
    LR.fit(X_train,y_train)
    y_prob_ = LR.predict_proba(X_test)[:,1]
    y_ = LR.predict(X_test)
    print('C =', C, 'using', solver, 'solver')
    print(confusion_matrix(y_test, y_, labels=[1,0]))
    print("AUC ROC score", roc_auc_score(y_test, y_prob_))

C = 0.01 using newton-cg solver
[[   2  195]
 [   3 2378]]
AUC ROC score 0.7720810050804061
C = 0.01 using lbfgs solver
[[   5  192]
 [   3 2378]]
AUC ROC score 0.7621930810114761
C = 0.01 using liblinear solver
[[   4  193]
 [   3 2378]]
AUC ROC score 0.7596837910957518
